Language.create iso_code: 'en', name: 'English'
Language.create iso_code: 'l0l', name: '1337speak'
Language.create iso_code: 'ar', name: 'Arabic'
Language.create iso_code: 'pt', name: 'Brazilian Portuguese'
Language.create iso_code: 'bg', name: 'Bulgarian'
Language.create iso_code: 'cze', name: 'Czech'
Language.create iso_code: 'da', name: 'Danish'
Language.create iso_code: 'nl', name: 'Dutch'
Language.create iso_code: 'fi', name: 'Finnish'
Language.create iso_code: 'fr', name: 'French'
Language.create iso_code: 'de', name: 'German'
Language.create iso_code: 'el', name: 'Greek'
Language.create iso_code: 'he', name: 'Hebrew'
Language.create iso_code: 'hu', name: 'Hungarian'
Language.create iso_code: 'it', name: 'Italian'
Language.create iso_code: 'jp', name: 'Japanese'
Language.create iso_code: 'ko', name: 'Korean'
Language.create iso_code: 'lv', name: 'Latvian'
Language.create iso_code: 'lt', name: 'Lithuanian'
Language.create iso_code: 'no', name: 'Norwegian'
Language.create iso_code: 'pl', name: 'Polish'
Language.create iso_code: 'pt_p', name: 'Portuguese'
Language.create iso_code: 'ro', name: 'Romanian'
Language.create iso_code: 'ru', name: 'Russian'
Language.create iso_code: 'chi', name: 'Chinese (Simplified)'
Language.create iso_code: 'sk', name: 'Slovak'
Language.create iso_code: 'es', name: 'Spanish'
Language.create iso_code: 'sv', name: 'Swedish'
Language.create iso_code: 'zho', name: 'Chinese (Traditional)'
Language.create iso_code: 'th', name: 'Thai'
Language.create iso_code: 'tr', name: 'Turkish'
